Using the correct Heroku env vars

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -54,21 +54,22 @@ fi
 if [ -e $BUILD_DIR/config.toml.template ]; then
     echo "\n-----> Found a config.toml.template"
 
-    # If this is not a production build, set the site's URL to the Heroku app URL
-    # Otherwise use the existing config.toml
-    if [ -d "$ENV_DIR" -a -e "$ENV_DIR/HUGO_PARENT_APP_NAME" -a -e "$ENV_DIR/HUGO_APP_NAME" ]; then
-        if ! [[ "$ENV_DIR/HUGO_PARENT_APP_NAME" == *"production"* ]]; then
-            export HUGO_PARENT_APP_NAME=$(cat "$ENV_DIR/HUGO_PARENT_APP_NAME")
-            export HUGO_APP_NAME=$(cat "$ENV_DIR/HUGO_APP_NAME")
-            echo "\n-----> This is not a production build based on the parent app name: $HUGO_PARENT_APP_NAME"
+    # Only proceed if we know what the Heroku app name is
+    if [ -d "$ENV_DIR" -a -e "$ENV_DIR/HEROKU_PARENT_APP_NAME" -a -e "$ENV_DIR/HEROKU_APP_NAME" ]; then
+        # If this is not a production build, set the site's URL to the Heroku app URL
+        # Otherwise use the existing config.toml
+        if ! [[ "$ENV_DIR/HEROKU_PARENT_APP_NAME" == *"production"* ]]; then
+            export HEROKU_PARENT_APP_NAME=$(cat "$ENV_DIR/HEROKU_PARENT_APP_NAME")
+            export HEROKU_APP_NAME=$(cat "$ENV_DIR/HEROKU_APP_NAME")
+            echo "\n-----> This is not a production build based on the parent app name: $HEROKU_PARENT_APP_NAME"
 
-            export HUGO_CONFIG_BASEURL="https://$HUGO_APP_NAME.herokuapp.com"
+            export HUGO_CONFIG_BASEURL="https://$HEROKU_APP_NAME.herokuapp.com"
             echo "\n-----> Generating staging config.toml with baseurl: $HUGO_CONFIG_BASEURL"
             sed -e 's@BSIDESROC_HUGO_URL@'${HUGO_CONFIG_BASEURL}'@' $BUILD_DIR/config.toml.template > $BUILD_DIR/config.toml
             echo "\n-----> config.toml generated"
         fi
     else
-        echo "\n-----> Could not find env vars HUGO_PARENT_APP_NAME and HUGO_APP_NAME, not generating staging config"
+        echo "\n-----> Could not find env vars HEROKU_PARENT_APP_NAME and HEROKU_APP_NAME, not generating staging config"
     fi
 fi
 
