Parent app name only available for review apps, and we don't need it since we can rely on app name alone. Removed.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -55,13 +55,13 @@ if [ -e $BUILD_DIR/config.toml.template ]; then
     echo "\n-----> Found a config.toml.template"
 
     # Only proceed if we know what the Heroku app name is
-    if [ -d "$ENV_DIR" -a -e "$ENV_DIR/HEROKU_PARENT_APP_NAME" -a -e "$ENV_DIR/HEROKU_APP_NAME" ]; then
+    if [ -d "$ENV_DIR" -a -e "$ENV_DIR/HEROKU_APP_NAME" ]; then
         # If this is not a production build, set the site's URL to the Heroku app URL
         # Otherwise use the existing config.toml
-        if ! [[ "$ENV_DIR/HEROKU_PARENT_APP_NAME" == *"production"* ]]; then
-            export HEROKU_PARENT_APP_NAME=$(cat "$ENV_DIR/HEROKU_PARENT_APP_NAME")
-            export HEROKU_APP_NAME=$(cat "$ENV_DIR/HEROKU_APP_NAME")
-            echo "\n-----> This is not a production build based on the parent app name: $HEROKU_PARENT_APP_NAME"
+        export HEROKU_APP_NAME=$(cat "$ENV_DIR/HEROKU_APP_NAME")
+
+        if ! [[ "$HEROKU_APP_NAME" == *"production"* ]]; then
+            echo "\n-----> This is not a production build based on the app name: $HEROKU_APP_NAME"
 
             export HUGO_CONFIG_BASEURL="https://$HEROKU_APP_NAME.herokuapp.com"
             echo "\n-----> Generating staging config.toml with baseurl: $HUGO_CONFIG_BASEURL"
@@ -69,7 +69,7 @@ if [ -e $BUILD_DIR/config.toml.template ]; then
             echo "\n-----> config.toml generated"
         fi
     else
-        echo "\n-----> Could not find env vars HEROKU_PARENT_APP_NAME and HEROKU_APP_NAME, not generating staging config"
+        echo "\n-----> Could not find env var HEROKU_APP_NAME, not generating staging config"
     fi
 fi
 
